if(WIN32)
  if(MSVC)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(lib_dir vc_x64_lib)
    else()
      set(lib_dir vc_lib)
    endif()
  endif()

  if(MINGW)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(lib_dir gcc_x64_lib)
    else()
      set(lib_dir gcc_lib)
    endif()
  endif()

  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(mswu_suffix d)
  else()
    set(mswu_suffix "")
  endif()
endif()
set(module_name wxWidgets)
if(EXISTS ${WXT_LIBS_DIR}/${WXT_BUILD_FLAG}/${module_name}/include)
  set(wxWidgets_ROOT_DIR ${WXT_LIBS_DIR}/${WXT_BUILD_FLAG}/${module_name})
endif()

if(NOT APPLE)
  # Try to find wxWidgets
  wxt_find_module(wxWidgets)
  if(${wxWidgets_FOUND})
    if(MSVC)
      set(tmp ${WXT_LIBS_DIR}/${WXT_BUILD_FLAG}/wxWidgets/include/msvc)
      include_directories(${tmp})
      link_directories(${WXT_LIBS_DIR}/${WXT_BUILD_FLAG}/wxWidgets/lib/${lib_dir})
      message(STATUS "[wxTools] Using ${tmp}/wx/setup.h")
    endif()
    return()
  endif()
endif()

# wxWidgets
wxt_add_github_module(${module_name} "https://github.com/wxWidgets/wxWidgets.git" "v3.3.1")
set(wxWidgets_LIBRARIES wx::core wx::aui)
include_directories(${CMAKE_SOURCE_DIR}/3rd/${module_name}/include)
if(MSVC)
  include_directories(${CMAKE_BINARY_DIR}/_deps/wxwidgets-build/lib/${vc_lib}/mswu${mswu_suffix})
endif()
if(NOT APPLE)
  wxt_install_module(${module_name})
endif()
