name: build-ubuntu
on:
  workflow_dispatch: # Enables manually
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
# on:
#  push:
#    branches:
#      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_IMAGE: ghcr.io/x-tools-author/wx-tools-ubuntu-20.04:x86_64

jobs:
  build-docker:
    name: Build width Docker
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build for linux
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}
          docker run --rm --privileged -v ${{ github.workspace }}:/workspace ${{ env.DOCKER_IMAGE }} /bin/bash -c "\
          cd /workspace && chmod +x ./scripts/ci-build-ubuntu-20.04.sh && ./scripts/ci-build-ubuntu-20.04.sh"
      - name: Upload Release Asset for Ubuntu
        run: |
          cd ${{ github.workspace }}/build
          find . -name "*.deb" -type f | while read file; do
            echo "find deb file: $file"
          done
          echo "---------------------------------------------------------------------------------"
          cd ${{ github.workspace }}/build
          find . -name "*.AppImage" -type f | while read file; do
            echo "find appimage file: $file"
          done
  build-system:
    name: Build with System
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build for linux
        run: |
          apt-get update -y
          apt-get install -y automake build-essential coreutils fuse git grep kmod libdbus* libegl1-mesa-dev libfontconfig1-dev libfreetype-dev libfreetype6-dev libglib2.0-dev libglu1-mesa-dev libgtk-3-dev libicu-dev libopengl-dev libtool libudev-dev libxcb-cursor-dev libxcb-xinerama0 libxkb* make mesa-common-dev ninja-build p7zip-full pkg-config software-properties-common tree unzip xvfb
          chmod +x ./scripts/ci-build-ubuntu-20.04.sh
          ./scripts/ci-build-ubuntu-20.04.sh"