name: build-test
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/commit-checker
        id: recent
        with:
          since_hours: 24
      - name: Use output
        run: |
          echo "Found? ${{ steps.recent.outputs.commits_found }}"
          echo "Count:  ${{ steps.recent.outputs.commits_count }}"
  test-1:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.commits_found == 'true' }}
    steps:
      - name: Recent Commits Found
        run: echo "There are recent commits, proceeding with tests."
  test-2:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.commits_found == 'false' }}
    steps:
      - name: No Recent Commits Found
        run: echo "No recent commits found, skipping tests."