name: build-windows
on:
  workflow_dispatch: # Enables manually
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
# on:
#  push:
#    branches:
#      - master
jobs:
  build-msvc:
    name: Build MSVC
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        arch: [x86, x64, x86_arm64]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "Ninja" ../
          cmake --build . --target wxTools
  build-minwg:
    name: Build MinGW
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # mingw 12.2, mingw 14.2
        os: [windows-2022, windows-2025]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: build-mingw
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "Ninja" ../
          cmake --build . --target wxTools
