name: build-ubuntu
on:
  workflow_dispatch: # Enables manually
  schedule:
    - cron: '0 0 * * *'
# on:
#  push:
#    branches:
#      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build for linux
        run: |
          git fetch --tags
          docker run --rm --privileged -v ${{ github.workspace }}:/workspace ${{ env.DOCKER_IMAGE }} /bin/bash -c "\
          cd /workspace && chmod +x ./scripts/ci-build-ubuntu-20.04.sh && ./scripts/ci-build-ubuntu-20.04.sh"


