name: build-test
on:
  workflow_dispatch:

jobs:
  build-test:
    name: Units Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: ctest
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "Ninja" ../
          cmake --build . --target test_crc
          cmake --build . --target test_decode
          cmake --build . --target test_encode
          cmake --build . --target test_table
          ctest