name: build-test
on:
  # schedule:
  #   - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build-test:
    name: Units Test
    runs-on: windows-2025
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Check Recent Commits
        uses: ./.github/actions/commit-checker
        id: recent
        with:
          since_hours: 24
      - name: ctest
        if: ${{ steps.recent.outputs.commits_found == 'true' }}
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "Ninja" ../
          cmake --build . --target test_crc
          cmake --build . --target test_decode
          cmake --build . --target test_encode
          cmake --build . --target test_table
          ctest