name: build-ubuntu
on:
  workflow_dispatch: # Enables manually
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
# on:
#  push:
#    branches:
#      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_IMAGE: ghcr.io/x-tools-author/wx-tools-ubuntu-20.04:x86_64

jobs:
  build-docker:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build for linux
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}
          docker run --rm --privileged -v ${{ github.workspace }}:/workspace ${{ env.DOCKER_IMAGE }} /bin/bash -c "\
          cd /workspace && chmod +x ./scripts/ci-build-ubuntu-20.04.sh && ./scripts/ci-build-ubuntu-20.04.sh"
      - name: Upload Release Asset for Ubuntu
        run: |
          cd ${{ github.workspace }}/build
          find . -name "*.deb" -type f | while read file; do
            echo "find deb file: $file"
          done
          echo "---------------------------------------------------------------------------------"
          cd ${{ github.workspace }}/build
          find . -name "*.AppImage" -type f | while read file; do
            echo "find appimage file: $file"
          done
  build-ubuntu:
    name: Build for Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build for linux
        run: |
          chmod +x ./scripts/install-dependencies.sh
          ./scripts/install-dependencies.sh
          chmod +x ./scripts/ci-build-ubuntu-20.04.sh
          ./scripts/ci-build-ubuntu-20.04.sh"