name: build-test
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/commit-checker
        id: recent
        with:
          since_hours: 24
      - name: Use output
        run: |
          echo "Found? ${{ steps.recent.outputs.commits_found }}"
          echo "Count:  ${{ steps.recent.outputs.commits_count }}"