name: build-macos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

#on:
#  push:
#    branches: [master]
#    paths-ignore:
#      - '*.md'
#      - '*.txt'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build for macos
        run: |
          git fetch --tags
          cmake --version
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF ../
          cmake --build . --target wxTools_pkg_dmg
          find . -name "*.pkg" -type f | while read file; do
            echo "find pkg file: $file"
          done
          find . -name "*.dmg" -type f | while read file; do
            echo "find dmg file: $file"
          done

